---
categories:
- 技术文章
date: '2009-08-02'
title: gtest中如何跳出当前测试案例
url: /2009/08/02/1536901/

---


在前面的[玩转gtest - 断言](http://www.cnblogs.com/coderzh/archive/2009/04/06/1430364.html "玩转Google开源C++单元测试框架Google Test系列(gtest)之二 - 断言")中， 我们提到了ASSERT_*系列的断言只是在当前函数返回，并非退出当前测试案例，因为ASSERT_*系列是通过return来实现的（因此 ASSERT_*系列不能在返回值不为void的函数内出现）。要退出当前测试案例，一个最简单的方法就是通过抛异常，然后让gtest捕获这一异常。示例如下：

<div class="cnblogs_code"><span style="color: #0000ff;">void</span><span style="color: #000000;">&nbsp;Func(</span><span style="color: #0000ff;">int</span><span style="color: #000000;">&nbsp;a,&nbsp;</span><span style="color: #0000ff;">int</span><span style="color: #000000;">&nbsp;b)
{
&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #0000ff;">throw</span><span style="color: #000000;">&nbsp;</span><span style="color: #800000;">"</span><span style="color: #800000;">b==0</span><span style="color: #800000;">"</span><span style="color: #000000;">;
&nbsp;&nbsp;&nbsp;&nbsp;EXPECT_EQ(</span><span style="color: #800080;">0</span><span style="color: #000000;">,&nbsp;a\b);
&nbsp;&nbsp;&nbsp;&nbsp;printf(</span><span style="color: #800000;">"</span><span style="color: #800000;">End&nbsp;of&nbsp;Func</span><span style="color: #800000;">"</span><span style="color: #000000;">);
}
<br />
TEST(FooTest,&nbsp;Demo1)
{
&nbsp;&nbsp;&nbsp;&nbsp;Func(</span><span style="color: #800080;">5</span><span style="color: #000000;">,&nbsp;</span><span style="color: #800080;">0</span><span style="color: #000000;">);
&nbsp;&nbsp;&nbsp;&nbsp;printf(</span><span style="color: #800000;">"</span><span style="color: #800000;">End&nbsp;Call&nbsp;Func(5,&nbsp;0)</span><span style="color: #800000;">"</span><span style="color: #000000;">);
}
<br />
</span><span style="color: #0000ff;">int</span><span style="color: #000000;">&nbsp;_tmain(</span><span style="color: #0000ff;">int</span><span style="color: #000000;">&nbsp;argc,&nbsp;_TCHAR</span><span style="color: #000000;">*</span><span style="color: #000000;">&nbsp;argv[])
{
&nbsp;&nbsp;&nbsp;&nbsp;testing::GTEST_FLAG(catch_exceptions)&nbsp;</span><span style="color: #000000;">=</span><span style="color: #000000;">&nbsp;</span><span style="color: #800080;">1</span><span style="color: #000000;">;
&nbsp;&nbsp;&nbsp;&nbsp;testing::InitGoogleTest(</span><span style="color: #000000;">&amp;</span><span style="color: #000000;">argc,&nbsp;argv);
&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #0000ff;">return</span><span style="color: #000000;">&nbsp;RUN_ALL_TESTS();
}</span></div>
(上面的两个printf函数都不会执行。)

要退出当前测试案例，你只需要两步：
1.设置catch_exception标志，在main函数或是在你的测试案例前都可以。
2.要跳出测试案例时，只需要通过throw抛出任意异常即可。

为何通过这种方法可以跳出当前测试案例，请参考[玩转gtest - 深入解析gtest](http://www.cnblogs.com/coderzh/archive/2009/04/11/1433744.html "玩转gtest - 深入解析gtest")。

需要注意的是：<span style="color: red;">假如使用的是TEST_F宏，跳出当前测试案例后，会执行TearDown()，因此不必当心TearDown中释放资源的操作不会执行。</span>

我认为一个好的测试案例，应该是在你的测试函数中，比如TEST宏内，<span style="color: red;">清晰的表达出你要测试的对象，以及预期的测试结果</span>。因此，通常情况下，EXPECT_*和 ASSERT_*应该尽量在测试函数中出现，而不是在测试函数内调用的另外函数或是里面很多层的函数内才出现。（比如上面的Func函数中的 EXPECT_EQ）。

**[温馨提示]：该文章由原博客园导入而来，如排版效果不佳，请移步：[http://www.cnblogs.com/coderzh/archive/2009/08/02/1536901.html](http://www.cnblogs.com/coderzh/archive/2009/08/02/1536901.html)**